### ISSUE TITLE
mbed-os-example-mesh-minimal is failing with radio-type set to ATMEL on K64F 

### ISSUE THREAD

**Issue by SenRamakri** [ARMmbed/mbed-os-example-mesh-minimal#122] opened 2017-09-01 23:10 UTC
Hello,

I'm trying to run mbed-os-example-mesh-minimal on K64F with ATMEL sheild(2.4) and its failing as below.

Connecting...

Connection failed! -3012

The mesh-type is set to MESH_THREAD. The code runs successfully with MCR20 though, and generates following output. 
Connecting...

connected. IP = fd00:db80::8c19:9b4a:fe08:bf74

**Comment by ciarmcom** [comment] 2017-09-11 11:51
ARM Internal Ref: ONME-3189

**Comment by SeppoTakalo** [comment] 2017-09-18 10:26
Hi @SenRamakri 

What kind of test environment are you running?
Can you share the `mbed_app.json` files from both border router and mesh client application.

Thanks.

**Comment by SeppoTakalo** [comment] 2017-10-04 10:24
Closing because not enough information is provided.
Both of these configurations are part of our CI testing and are working fine.
I cannot see any problems here.

Please re-open if you have more information or the problem is still valid.

**Closed by SeppoTakalo** 2017-10-04 10:24 UTC
Labels: mirrored
